import React, { useRef, useEffect } from 'react';
import { Send, MoreVertical, Search, Smile, Paperclip, Mic, ArrowLeft } from 'lucide-react';
import { useChat } from './hooks/useChat';
import ChatBubble from './components/ChatBubble';
import './App.css';

const App: React.FC = () => {
  const { messages, inputText, setInputText, handleSend, handleReset } = useChat();
  
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'auto' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      const newHeight = Math.min(textareaRef.current.scrollHeight, 100);
      textareaRef.current.style.height = `${newHeight}px`;
    }
  }, [inputText]);

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="app-container">
       {/* Main Container */}
      <div className="main-window">
        
        {/* WhatsApp Header */}
        <header className="header">
          <div className="header-left">
            <button className="back-btn">
                <ArrowLeft size={24} />
            </button>
            <div className="avatar-container">
                {/* Meta AI Ring Logo */}
                <div className="meta-ring">
                    <div className="meta-avatar-inner">
                        <div className="meta-gradient-overlay"></div>
                        <img 
                            src="https://images.sftcdn.net/images/t_app-icon-m/p/7accf6af-ce49-43eb-a290-c87bdd396d5a/1907296832/arattai-logo" 
                            alt="Meta AI" 
                            className="meta-logo" 
                        />
                    </div>
                </div>
                {/* Online Indicator */}
                <span className="online-indicator"></span>
            </div>
            
            <div className="header-info">
              <h1 className="header-title">Arattai AI</h1>
              <p className="header-subtitle">
                 with Llama 3
              </p>
            </div>
          </div>

          <div className="header-actions">
             <div className="divider mobile-hide"></div>
             <button className="icon-btn"><Search size={20} /></button>
             <button 
                onClick={handleReset}
                className="icon-btn" 
                title="Clear Chat"
             >
                <MoreVertical size={20} />
             </button>
          </div>
        </header>

        {/* Chat Area Background */}
        <div className="chat-background"></div>

        {/* Messages List */}
        <div className="messages-list">
          {/* Encryption Notice */}
          <div className="encryption-notice">
            <div className="notice-box">
              Messages are generated by AI. Some messages may be inaccurate.
            </div>
          </div>

          {messages.length === 0 && (
             <div className="empty-state">
                 <div className="welcome-ring">
                    <div className="welcome-inner">
                        <div className="welcome-overlay"></div>
                    </div>
                 </div>
                 <h2 className="empty-title">Ask Meta AI anything</h2>
                 <p className="empty-desc">
                     Get answers, learn something new, or translate languages instantly.
                 </p>
                 
                 <div className="suggestion-grid">
                    <button onClick={() => handleSend("Tell me a fun fact")} className="suggestion-btn">
                        💡 Tell me a fun fact
                    </button>
                    <button onClick={() => handleSend("Write a React component")} className="suggestion-btn">
                        ⚛️ Write a React component
                    </button>
                    <button onClick={() => handleSend("Translate 'Hello' to Tamil")} className="suggestion-btn">
                        🌏 Translate to Tamil
                    </button>
                     <button onClick={() => handleSend("Help me plan a trip")} className="suggestion-btn">
                        ✈️ Plan a trip
                    </button>
                 </div>
             </div>
          )}

          {messages.map((msg) => (
            <ChatBubble key={msg.id} message={msg} />
          ))}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="input-area">
            <button className="icon-btn">
                <Smile size={24} />
            </button>
            <button className="icon-btn">
                <Paperclip size={24} />
            </button>

            <div className="input-wrapper">
                <textarea
                    ref={textareaRef}
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    onKeyDown={onKeyDown}
                    placeholder="Message"
                    className="chat-input"
                    rows={1}
                />
            </div>

            {inputText.trim() ? (
                <button 
                    onClick={() => handleSend()} 
                    className="send-btn"
                >
                    <Send size={20} fill="white" />
                </button>
            ) : (
                <button className="icon-btn">
                    <Mic size={24} />
                </button>
            )}
        </div>
      </div>
    </div>
  );
};

export default App;